[workspace]
resolver = "2"
members = [
    "crates/*"
]
[workspace.package]
edition = "2024"
license = "MIT"
repository = "https://github.com/hardfist/unpack"

[workspace.dependencies]
unpack = { path = "./crates/unpack"}
derive-new = { version = "0.6.0"}
index_vec = { version = "0.1.3"}